/* Generated By:JavaCC: Do not edit this line. alikeConstants.java */
package traductor;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface alikeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 1;
  /** RegularExpression Id. */
  int DIGIT = 2;
  /** RegularExpression Id. */
  int UNDERSCORE = 3;
  /** RegularExpression Id. */
  int tSPACE = 4;
  /** RegularExpression Id. */
  int tNL = 5;
  /** RegularExpression Id. */
  int tTAB = 6;
  /** RegularExpression Id. */
  int tENTER = 7;
  /** RegularExpression Id. */
  int tCOMENTARIO = 8;
  /** RegularExpression Id. */
  int tBOOL = 9;
  /** RegularExpression Id. */
  int tCHAR = 10;
  /** RegularExpression Id. */
  int tCHARACTER = 11;
  /** RegularExpression Id. */
  int tINTEGER = 12;
  /** RegularExpression Id. */
  int tSTRING = 13;
  /** RegularExpression Id. */
  int tNULL = 14;
  /** RegularExpression Id. */
  int tARRAY = 15;
  /** RegularExpression Id. */
  int tCONST_INT = 16;
  /** RegularExpression Id. */
  int tCONST_CHAR = 17;
  /** RegularExpression Id. */
  int tCONST_STRING = 18;
  /** RegularExpression Id. */
  int tASIGN = 19;
  /** RegularExpression Id. */
  int tSUM = 20;
  /** RegularExpression Id. */
  int tRES = 21;
  /** RegularExpression Id. */
  int tEQU = 22;
  /** RegularExpression Id. */
  int tGT = 23;
  /** RegularExpression Id. */
  int tLT = 24;
  /** RegularExpression Id. */
  int tGE = 25;
  /** RegularExpression Id. */
  int tLE = 26;
  /** RegularExpression Id. */
  int tDIF = 27;
  /** RegularExpression Id. */
  int tMUL = 28;
  /** RegularExpression Id. */
  int tMOD = 29;
  /** RegularExpression Id. */
  int tDIV = 30;
  /** RegularExpression Id. */
  int tNOT = 31;
  /** RegularExpression Id. */
  int tAND = 32;
  /** RegularExpression Id. */
  int tOR = 33;
  /** RegularExpression Id. */
  int tIF = 34;
  /** RegularExpression Id. */
  int tELIF = 35;
  /** RegularExpression Id. */
  int tELSE = 36;
  /** RegularExpression Id. */
  int tTHEN = 37;
  /** RegularExpression Id. */
  int tWHILE = 38;
  /** RegularExpression Id. */
  int tLOOP = 39;
  /** RegularExpression Id. */
  int tTRUE = 40;
  /** RegularExpression Id. */
  int tFALSE = 41;
  /** RegularExpression Id. */
  int tPROCEDURE = 42;
  /** RegularExpression Id. */
  int tFUNCTION = 43;
  /** RegularExpression Id. */
  int tIS = 44;
  /** RegularExpression Id. */
  int tREF = 45;
  /** RegularExpression Id. */
  int tOF = 46;
  /** RegularExpression Id. */
  int tBEGIN = 47;
  /** RegularExpression Id. */
  int tEND = 48;
  /** RegularExpression Id. */
  int tRETURN = 49;
  /** RegularExpression Id. */
  int tASSERT = 50;
  /** RegularExpression Id. */
  int tPRE = 51;
  /** RegularExpression Id. */
  int tSKIP_LN = 52;
  /** RegularExpression Id. */
  int tPUT = 53;
  /** RegularExpression Id. */
  int tPUT_LN = 54;
  /** RegularExpression Id. */
  int tGET = 55;
  /** RegularExpression Id. */
  int tCHAR2INT = 56;
  /** RegularExpression Id. */
  int tINT2CHAR = 57;
  /** RegularExpression Id. */
  int tPUNTO = 58;
  /** RegularExpression Id. */
  int tCOMA = 59;
  /** RegularExpression Id. */
  int tDOSPUNTOS = 60;
  /** RegularExpression Id. */
  int tDOBLEPUNTO = 61;
  /** RegularExpression Id. */
  int tPUNTOCOMA = 62;
  /** RegularExpression Id. */
  int tCORCHETES_OPEN = 63;
  /** RegularExpression Id. */
  int tCORCHETES_CLOSE = 64;
  /** RegularExpression Id. */
  int tPARENTESIS_OPEN = 65;
  /** RegularExpression Id. */
  int tPARENTESIS_CLOSE = 66;
  /** RegularExpression Id. */
  int tID = 67;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<LETTER>",
    "<DIGIT>",
    "\"_\"",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "<tCOMENTARIO>",
    "\"boolean\"",
    "\"char\"",
    "\"character\"",
    "\"integer\"",
    "\"string\"",
    "\"null\"",
    "\"array\"",
    "<tCONST_INT>",
    "<tCONST_CHAR>",
    "<tCONST_STRING>",
    "\":=\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"/=\"",
    "\"*\"",
    "\"mod\"",
    "\"/\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"if\"",
    "\"elsif\"",
    "\"else\"",
    "\"then\"",
    "\"while\"",
    "\"loop\"",
    "\"true\"",
    "\"false\"",
    "\"procedure\"",
    "\"function\"",
    "\"is\"",
    "\"ref\"",
    "\"of\"",
    "\"begin\"",
    "\"end\"",
    "\"return\"",
    "\"assert:\"",
    "\"pre:\"",
    "\"skip_line\"",
    "\"put\"",
    "\"put_line\"",
    "\"get\"",
    "\"char2int\"",
    "\"int2char\"",
    "\".\"",
    "\",\"",
    "\"..\"",
    "\":\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "<tID>",
  };

}
